### ISSUE TITLE
prefixかメンションでの呼び出しをswitchする

### ISSUE THREAD

**Issue by atomu21263** [takanakahiko/discord-tts#10]
メンションで呼び出しだとTABで補完した してないなどでのスペースが原因で飛んでこない可能性があるため

**Comment by takanakahiko** [comment]
いいですね！良さそうなので、可能であれば Pull requests で変更をいただけると嬉しいです！
時間がなさそうなら僕が実装しても構いません。

**Comment by takanakahiko** [comment]
#12 で対応済み
